### ISSUE TITLE
Add content to "About"

### ISSUE THREAD

**Issue by denmarkcontrevida2017** [dalelicious/negrosPisoWifi#11]

**Comment by denmarkcontrevida2017** [comment]
Negros Piso WiFi is an official distributor of Ado Piso Wifi system. "Piso" is the term for "coins" here in the Philippines while "Peso" is our currency. 

Mobile data costs a lot more than ever. In the Philippines, most people will likely to spend money to access the internet for 50php only gets 100-300mb which is not enough for most people. Ado Piso Wifi created a software to give people an instant access to people and a chance for people to have their own business. The business costs from 19k-22k depending on the distributor. It has different designs for each location and providers. 

Since most people nowadays own a smartphone with wifi capability, we can utilize the unlimited plans of our telcos by sharing it using wifi with very minimal cost. We, from Bacolod City, are the ones who work hard to design, build and supply the machine all over Negros Occidental.

**Comment by dalelicious** [comment]
Is this a new page that would be added?

**Comment by denmarkcontrevida2017** [comment]
This was from the footer, it seems you remove everything

**Comment by dalelicious** [comment]
Done
