### ISSUE TITLE
Meta head

### ISSUE THREAD

**Issue by denmarkcontrevida2017** [dalelicious/negrosPisoWifi#18]
<meta property="og:url"                content="https://negrospisowifi.com" />
		<meta property="og:type"               content="article" />
		<meta property="og:title"              content="Start Small. Earn Big." />
		<meta property="og:description"        content="Start your business with Wifi Vendo Machine" />
		<meta property="og:image"              content="https://negrospisowifi/include/img/logo.png"

**Comment by dalelicious** [comment]
Done
